security:
  oauth2:
    resource:
      token-info-uri: http://grampus-service-auth/oauth/check_token
    client:
      client-id: client_system
      client-secret: 123456

spring:
  datasource:
    url: jdbc:mysql://192.168.8.110:3306/grampus_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 192.168.8.110
    port: 6379
    password: root
    timeout: 6000ms
    lettuce:
      pool:
        max-idle: 300
        min-idle: 5
        max-active: 1000
        max-wait: 20000ms
#  rabbitmq:
#    addresses: 192.168.0.97:5672,192.168.0.142:5672,192.168.0.176:5672
#    username: grampus
#    password: grampus
#    virtual-host: /grampus
#    listener:
#      simple:
#        acknowledge-mode: manual
#      direct:
#        acknowledge-mode: manual

logging:
  level:
    org.springframework.security: DEBUG