spring:
  datasource:
    url: jdbc:mysql://192.168.8.110:3306/grampus_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 192.168.8.110
    port: 6379
    password: root
    timeout: 6000ms
    lettuce:
      pool:
        max-idle: 300
        min-idle: 5
        max-active: 1000
        max-wait: 20000ms