CREATE TABLE `member_info`
(
    `id`                INT NOT NULL AUTO_INCREMENT COMMENT '数据ID',
    `member_no`         VARCHAR(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci   DEFAULT NULL COMMENT '会员号唯一标识',
    `nickname`          VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  DEFAULT NULL COMMENT '昵称',
    `member_type`       TINYINT                                                       DEFAULT NULL COMMENT '会员类型(1未认证 2真人 3女神 4认证撤销)',
    `verify_type`       TINYINT                                                       DEFAULT '1' COMMENT '会员认证中间状态(1默认 2真人认证审核中 3女神认证审核中 4真人认证不通过 5女神认证不通过)',
    `revoke_type`       TINYINT                                                       DEFAULT NULL COMMENT '会员认证撤销前状态(1默认 2真人 3女神)',
    `area_code`         VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  DEFAULT NULL COMMENT '手机区域编号',
    `phone`             VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  DEFAULT NULL COMMENT '手机号码',
    `gender`            TINYINT(1) DEFAULT NULL COMMENT '性别(1男 2女)',
    `avatar_id`         INT                                                           DEFAULT NULL COMMENT '头像ID',
    `verify_avatar_id`  INT                                                           DEFAULT NULL COMMENT '待审核头像ID',
    `face_id`           INT                                                           DEFAULT NULL COMMENT '面容ID',
    `remainder_coin`    INT                                                           DEFAULT '0' COMMENT '剩余点数',
    `consumption_coin`  INT                                                           DEFAULT '0' COMMENT '消费点数',
    `withdraw_coin`     INT                                                           DEFAULT '0' COMMENT '可提现点数',
    `source_type`       VARCHAR(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci   DEFAULT '1' COMMENT '来源类型(1默认(无邀请码) 2系统邀请 3推广邀请 4专属渠道邀请 5马甲号 6发布商女士)',
    `source_channel`    VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  DEFAULT NULL COMMENT '来源渠道',
    `certify_pattern`   TINYINT                                                       DEFAULT NULL COMMENT '认证状态变更方式(1系统 2人工)',
    `certify_by`        INT                                                           DEFAULT NULL COMMENT '认证状态变更操作者(本人NULL 系统用户ID)',
    `certify_date`      DATETIME(3) DEFAULT NULL COMMENT '认证状态变更日期(真人,女神,撤销)',
    `invisible`         TINYINT(1) DEFAULT '0' COMMENT '隐身状态(0正常 1隐身)',
    `language`          VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  DEFAULT NULL COMMENT '用户语言(zh-CN zh-HK en-US)',
    `country_id`        BIGINT                                                        DEFAULT NULL COMMENT '当前国家ID',
    `province_id`       BIGINT                                                        DEFAULT NULL COMMENT '当前省份ID',
    `city_id`           BIGINT                                                        DEFAULT NULL COMMENT '当前城市ID',
    `resident_city_id`  VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '常驻城市ID',
    `career_id`         BIGINT                                                        DEFAULT NULL COMMENT '职业ID',
    `birthday`          DATETIME(3) DEFAULT NULL COMMENT '出生日期',
    `height`            INT                                                           DEFAULT NULL COMMENT '身高(cm)',
    `weight`            INT                                                           DEFAULT NULL COMMENT '体重(kg)',
    `intro`             VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '自我介绍',
    `password`          VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci       DEFAULT NULL COMMENT '密码',
    `email`             VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci        DEFAULT NULL COMMENT '邮箱',
    `status`            TINYINT                                                       DEFAULT NULL COMMENT '账号状态(1正常 2编辑 3冻结 4异常)',
    `abnormal`          TINYINT                                                       DEFAULT NULL COMMENT '异常状态(1正常 2异常)',
    `online_status`     TINYINT(1) DEFAULT '0' COMMENT '在线状态(0离线 1在线)',
    `register_type`     VARCHAR(16) CHARACTER SET utf8 COLLATE utf8_unicode_ci        DEFAULT '' COMMENT '注册方式(password sms acs oauth_google)',
    `register_ip`       VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci        DEFAULT NULL COMMENT '注册IP',
    `register_date`     DATETIME(3) DEFAULT NULL COMMENT '注册时间',
    `last_login_ip`     VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci        DEFAULT NULL COMMENT '最后登录IP',
    `last_login_date`   DATETIME(3) DEFAULT NULL COMMENT '最后登录时间',
    `last_login_os`     VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci        DEFAULT NULL COMMENT '最后登录系统',
    `last_device_type`  TINYINT                                                       DEFAULT '0' COMMENT '最后登录应用类型(1Android 2IOS 3Android-Google 4IOS-SE)',
    `registration_type` TINYINT                                                       DEFAULT NULL COMMENT '推送平台(1极光推送 2FCM推送)',
    `registration_id`   VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci       DEFAULT NULL COMMENT '推送登记ID',
    `wx_open_id`        VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci        DEFAULT NULL COMMENT '微信公众号openid',
    `google_id`         VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci        DEFAULT NULL COMMENT '谷歌用户唯一标识',
    `del_flag`          TINYINT(1) DEFAULT NULL COMMENT '删除标志(0正常 1删除)',
    PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='会员信息表';