spring:
  cloud:
    gateway:
      routes:
        - id: grampus-service-auth
          uri: lb://grampus-service-auth
          predicates:
            - Path=/auth/**
#          filters:
#            - name: RequestBodyDecoderFilter
#              args: {}
#            - name: RequestNonceFilter
#              args: {}
#            - name: ResponseBodyEncoderFilter
#              args: {}
          order: 100
        - id: grampus-service-admin
          uri: lb://grampus-service-admin
          predicates:
            - Path=/admin/**
#          filters:
#            - name: RequestBodyDecoderFilter
#              args: {}
#            - name: RequestNonceFilter
#              args: {}
#            - name: ResponseBodyEncoderFilter
#              args: {}
          order: 99